### PR TITLE
WIP: implement retry option 

### PR DESCRIPTION
**Pull request by dkropachev**
Fixes https://github.com/scylladb/scylla-bench/issues/63

### CODE REVIEW

**Comment by roydahan** [comment]
@dkropachev any progress on this one?

**Comment by dkropachev** [comment]
> @dkropachev any progress on this one?

Did not touch it for months, but it is still in plan to finish it

**Comment by roydahan** [comment]
@dkropachev is that a hint that you're not planning on doing this? :)

**Comment by dkropachev** [comment]
> @dkropachev is that a hint that you're not planning on doing this? :)

@roydahan, hi roy, how are you ?

I want to finish it up, but there was other [PR](https://github.com/scylladb/scylla-bench/pull/93) that had been dangling there, I thought that team does not want to work on a tool anymore and closed both of them.
If you don't think so, I will glad to reopen both and finish this one up

**Comment by roydahan** [comment]
> 

I'm good, hope you as well :)

We don't want to work with the tool, but we have to :)
We will try let @vponomaryov work on that next week so we won't bother you.

**Comment by vponomaryov** [comment]
Implemented here: https://github.com/scylladb/scylla-bench/pull/96

**Pull request closed without merging**
