### PR TITLE
Add precommit

### PR DESCRIPTION
**Pull request by dkropachev**
Looking to improve code quality

### CODE REVIEW

**Comment by psarna** [comment]
Somebody fluent in golang and its environment should review this one - I have no idea what's happening here, why some new dependencies from github appeared, etc. I'm sure there's a reason for that, but I'm in no position to judge because I never coded a single program in go (:

**Comment by dkropachev** [comment]
@sitano , Ivan could you please take a look

**Review by nyh — CHANGES_REQUESTED** [review]
The commit messages are too terse: "add precommit" and "make it happy" are the full text you wrote :-( I had to do a lot of soul-searching and guessing before I finally understood that "precommit" means set up a tool to check the style of the code, and "make it happy" means changing the style to fit what this checker tool wants.

Beyond better explanations, I would like to see a lot more talk about the motivation of this patch: Why is style-checking important to you and/or to our project? How did you select the specific set of random-looking tools from all over github.com to use - are those the tools everyone uses? 

As a non-Go expert I also have to ask about go.mod - where do all those weird version number and hashes come from? What motivated you to upgrade go-spew (for example) from v1.1.0 to v1.1.1 - or was this just some sort of automatic process taking the latest version?

**Comment by sitano** [comment]
My opinion is that such tools as style code checking must be part of the GitHub hooks / CI/CD / checks before merge, and not be implemented as git pre-commit hooks as it is for example done here:

- https://github.com/scylladb/siren/tree/master/.github
- https://docs.github.com/en/actions/guides/about-continuous-integration
- https://github.com/mvdan/github-actions-golang

The level on which those tools must check if the commit satisfy rules must be Git Hub Pull Request. Being implemented as pre-commit hooks it seems to me they will prevent efficient work with git rebase and wip branches.

**Comment by sitano** [comment]
An example of GitHub CI in PR https://github.com/cockroachdb/cockroach/pull/66246

**Comment by sitano** [comment]
> have to ask about go.mod - where do all those weird version number and hashes come from?

`go.mod` is part of the standard native golang dependency management system called `go mod`. it contains versions of all dependencies so you can have reproducible builds.

> What motivated you to upgrade go-spew (for example) from v1.1.0 to v1.1.1 - or was this just some sort of automatic process taking the latest version?

In Go it's a usual practice to update packages to the latest version. Not much sense to keep them outdated. But you can choose to update only 1 dependency or all of them. The process of updating / adding something requires you to solve and update dependency constraints in the dep tree and it may require other pckgs to also bump their versions.

**Pull request closed without merging**
